name: mall_litemall_demo
description: A new Flutter project.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  dio: #^3.0.9
  #持久化
  shared_preferences: #^0.5.6+3
  # fluro: ^1.6.1  #路由
  flutter_html:  #加载html文本
  fluttertoast: #^3.1.3  #提示框
  flutter_easyloading: #^1.1.4  #loading

  flutter_screenutil: #^1.1.0  #适配工具
  flutter_swiper: #^1.1.6       #轮播图
  url_launcher:  #拨打电话\打开浏览器、邮件、短信
  flui: #^0.9.0    #UI库
  # flutter_easyrefresh:     #刷新
  pull_to_refresh: #^1.5.8   #刷新
  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: #^0.1.3
  
  # json转Model 三个库
  json_annotation: #^3.0.1
  #状态管理
  provide: #^1.0.2

  #状态管理 fish-redux
  fish_redux:  #^0.3.1
  #滑动到指定位置
  scroll_to_index:

  #高德地图
  amap_map_fluttify:
  permission_handler: #权限

dev_dependencies:
  flutter_test:
    sdk: flutter
  #启用国际化
  flutter_localizations:
    sdk: flutter
  #json转model
  json_serializable: #^3.2.5
  build_runner: #^1.8.0
  fluro:  #路由
   git: git://github.com/theyakka/fluro.git


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  assets:
    - static/
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
